name: PR branch check

on:
  pull_request:   # run on all PRs
    types: [opened, synchronize, edited]

jobs:
  enforce-dev-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" = "main" ]; then
            if [ "${{ github.event.pull_request.head.ref }}" != "dev" ]; then
              echo "❌ Only PRs from 'dev' are allowed to merge into 'main'."
              exit 1
            else
              echo "✅ PR source branch is dev. All good!"
            fi
          else
            echo "ℹ️ Target branch is not main, skipping check."
          fi
